=== cristobalvelasco8/EjerciciosLMSGI/examen.dtd
<!ELEMENT futbol (#PCDATA |futbolista| partido)*>
<!ENTITY % atributoLugar "lugar (Madrid | Delantero | Japon) 'Madrid'">
<!ELEMENT futbolista EMPTY>
<!ATTLIST futbolista nombre ID #REQUIRED>
<!ATTLIST futbolista compaÃ±ero IDREF #IMPLIED>
<!ATTLIST futbolista amigode IDREFS #IMPLIED>
<!ATTLIST futbolista rol CDATA #FIXED "portero">
<!ELEMENT partido (equipo, (campo | posicion ), puntuacion?)>
<!ELEMENT equipo (#PCDATA)>
<!ELEMENT puntuacion (valoracion+)>
<!ELEMENT valoracion (#PCDATA)>
<!ELEMENT campo EMPTY>
<!ATTLIST campo %atributoLugar;>
<!ELEMENT posicion EMPTY>
<!ATTLIST posicion %atributoLugar;>
<!ENTITY madrid "Un lugar precioso">

=== cristobalvelasco8/EjerciciosLMSGI/examen.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE futbol SYSTEM "examen.dtd">
<futbol>
	Real Madrid
	<futbolista nombre="Sergio" amigode="Courtois" />
	<futbolista nombre="Lucas" compañero="Benzema" />
	<futbolista nombre="Benzema" compañero="Lucas" />
	<futbolista nombre="Courtois" rol="portero" />
	<partido>
		<equipo>Barcelona</equipo>
		<campo lugar="Madrid" />
		<puntuacion>
			<valoracion>Una web que le da un 9</valoracion>
			<valoracion>Una web que le da un 10</valoracion>
		</puntuacion>
	</partido>
	<partido>
		<equipo>Malaga - &madrid;</equipo>
		<posicion lugar="Delantero" />
		<puntuacion>
			<valoracion>Una web que le da un 9</valoracion>
			<valoracion>Una web que le da un 10</valoracion>
		</puntuacion>
	</partido>
</futbol>
